openapi: 3.0.0
info:
  title: API RedAntiSocial 🕶️
  version: 1.0.0
  description: Documentación oficial de las rutas de la RedAntiSocial.

# Definimos el servidor local donde corre la API
servers:
  - url: http://localhost:3000
    description: Servidor de Desarrollo

paths:
  # ------ RUTA: /usuarios ------
  /usuarios:
    # 1. Método GET (Obtener usuarios)
    get:
      summary: Obtiene la lista de todos los usuarios
      description: Devuelve un arreglo con todos los usuarios registrados en la red antisocial.
      responses:
        "200":
          description: Lista de usuarios obtenida con éxito.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Usuario" # Hacemos referencia al molde de abajo

    # 2. Método POST (Crear un usuario)
    post:
      summary: Registrar un nuevo usuario
      description: Recibe los datos del usuario en el cuerpo de la petición (body) y lo registra.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NuevoUsuario"
      responses:
        "201":
          description: Usuario creado exitosamente.
        "400":
          description: Error en los datos enviados (Falta email o contraseña).

# ------ COMPONENTES REUTILIZABLES (Moldes de datos) ------
components:
  schemas:
    # Lo que se necesita para CREAR un usuario
    NuevoUsuario:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          example: "juan_antisocial"
        email:
          type: string
          example: "juan@correo.com"
        password:
          type: string
          example: "secreto123"

    # Lo que DEVUELVE el servidor (incluye el ID generado)
    Usuario:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: "juan_antisocial"
        email:
          type: string
          example: "juan@correo.com"
